# emoji-cheat-sheet

[![build](https://travis-ci.org/ikatyang/emoji-cheat-sheet.svg?branch=master)](https://travis-ci.org/ikatyang/emoji-cheat-sheet)

This cheat sheet is automatically generated from [GitHub Emoji API](https://api.github.com/emojis) and [Emoji Cheat Sheet](http://www.emoji-cheat-sheet.com)

## Table of Contents

- [People](#people)
- [Nature](#nature)
- [Objects](#objects)
- [Places](#places)
- [Symbols](#symbols)
- [Uncategorized](#uncategorized)

### People

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :bowtie: | `:bowtie:`  |  :smile: | `:smile:` |
| [top](#table-of-contents) | :laughing: | `:laughing:`  |  :blush: | `:blush:` |
| [top](#table-of-contents) | :smiley: | `:smiley:`  |  :relaxed: | `:relaxed:` |
| [top](#table-of-contents) | :smirk: | `:smirk:`  |  :heart_eyes: | `:heart_eyes:` |
| [top](#table-of-contents) | :kissing_heart: | `:kissing_heart:`  |  :kissing_closed_eyes: | `:kissing_closed_eyes:` |
| [top](#table-of-contents) | :flushed: | `:flushed:`  |  :relieved: | `:relieved:` |
| [top](#table-of-contents) | :satisfied: | `:satisfied:`  |  :grin: | `:grin:` |
| [top](#table-of-contents) | :wink: | `:wink:`  |  :stuck_out_tongue_winking_eye: | `:stuck_out_tongue_winking_eye:` |
| [top](#table-of-contents) | :stuck_out_tongue_closed_eyes: | `:stuck_out_tongue_closed_eyes:`  |  :grinning: | `:grinning:` |
| [top](#table-of-contents) | :kissing: | `:kissing:`  |  :kissing_smiling_eyes: | `:kissing_smiling_eyes:` |
| [top](#table-of-contents) | :stuck_out_tongue: | `:stuck_out_tongue:`  |  :sleeping: | `:sleeping:` |
| [top](#table-of-contents) | :worried: | `:worried:`  |  :frowning: | `:frowning:` |
| [top](#table-of-contents) | :anguished: | `:anguished:`  |  :open_mouth: | `:open_mouth:` |
| [top](#table-of-contents) | :grimacing: | `:grimacing:`  |  :confused: | `:confused:` |
| [top](#table-of-contents) | :hushed: | `:hushed:`  |  :expressionless: | `:expressionless:` |
| [top](#table-of-contents) | :unamused: | `:unamused:`  |  :sweat_smile: | `:sweat_smile:` |
| [top](#table-of-contents) | :sweat: | `:sweat:`  |  :disappointed_relieved: | `:disappointed_relieved:` |
| [top](#table-of-contents) | :weary: | `:weary:`  |  :pensive: | `:pensive:` |
| [top](#table-of-contents) | :disappointed: | `:disappointed:`  |  :confounded: | `:confounded:` |
| [top](#table-of-contents) | :fearful: | `:fearful:`  |  :cold_sweat: | `:cold_sweat:` |
| [top](#table-of-contents) | :persevere: | `:persevere:`  |  :cry: | `:cry:` |
| [top](#table-of-contents) | :sob: | `:sob:`  |  :joy: | `:joy:` |
| [top](#table-of-contents) | :astonished: | `:astonished:`  |  :scream: | `:scream:` |
| [top](#table-of-contents) | :neckbeard: | `:neckbeard:`  |  :tired_face: | `:tired_face:` |
| [top](#table-of-contents) | :angry: | `:angry:`  |  :rage: | `:rage:` |
| [top](#table-of-contents) | :triumph: | `:triumph:`  |  :sleepy: | `:sleepy:` |
| [top](#table-of-contents) | :yum: | `:yum:`  |  :mask: | `:mask:` |
| [top](#table-of-contents) | :sunglasses: | `:sunglasses:`  |  :dizzy_face: | `:dizzy_face:` |
| [top](#table-of-contents) | :imp: | `:imp:`  |  :smiling_imp: | `:smiling_imp:` |
| [top](#table-of-contents) | :neutral_face: | `:neutral_face:`  |  :no_mouth: | `:no_mouth:` |
| [top](#table-of-contents) | :innocent: | `:innocent:`  |  :alien: | `:alien:` |
| [top](#table-of-contents) | :yellow_heart: | `:yellow_heart:`  |  :blue_heart: | `:blue_heart:` |
| [top](#table-of-contents) | :purple_heart: | `:purple_heart:`  |  :heart: | `:heart:` |
| [top](#table-of-contents) | :green_heart: | `:green_heart:`  |  :broken_heart: | `:broken_heart:` |
| [top](#table-of-contents) | :heartbeat: | `:heartbeat:`  |  :heartpulse: | `:heartpulse:` |
| [top](#table-of-contents) | :two_hearts: | `:two_hearts:`  |  :revolving_hearts: | `:revolving_hearts:` |
| [top](#table-of-contents) | :cupid: | `:cupid:`  |  :sparkling_heart: | `:sparkling_heart:` |
| [top](#table-of-contents) | :sparkles: | `:sparkles:`  |  :star: | `:star:` |
| [top](#table-of-contents) | :star2: | `:star2:`  |  :dizzy: | `:dizzy:` |
| [top](#table-of-contents) | :boom: | `:boom:`  |  :collision: | `:collision:` |
| [top](#table-of-contents) | :anger: | `:anger:`  |  :exclamation: | `:exclamation:` |
| [top](#table-of-contents) | :question: | `:question:`  |  :grey_exclamation: | `:grey_exclamation:` |
| [top](#table-of-contents) | :grey_question: | `:grey_question:`  |  :zzz: | `:zzz:` |
| [top](#table-of-contents) | :dash: | `:dash:`  |  :sweat_drops: | `:sweat_drops:` |
| [top](#table-of-contents) | :notes: | `:notes:`  |  :musical_note: | `:musical_note:` |
| [top](#table-of-contents) | :fire: | `:fire:`  |  :hankey: | `:hankey:` |
| [top](#table-of-contents) | :poop: | `:poop:`  |  :shit: | `:shit:` |
| [top](#table-of-contents) | :+1: | `:+1:`  |  :thumbsup: | `:thumbsup:` |
| [top](#table-of-contents) | :-1: | `:-1:`  |  :thumbsdown: | `:thumbsdown:` |
| [top](#table-of-contents) | :ok_hand: | `:ok_hand:`  |  :punch: | `:punch:` |
| [top](#table-of-contents) | :facepunch: | `:facepunch:`  |  :fist: | `:fist:` |
| [top](#table-of-contents) | :v: | `:v:`  |  :wave: | `:wave:` |
| [top](#table-of-contents) | :hand: | `:hand:`  |  :raised_hand: | `:raised_hand:` |
| [top](#table-of-contents) | :open_hands: | `:open_hands:`  |  :point_up: | `:point_up:` |
| [top](#table-of-contents) | :point_down: | `:point_down:`  |  :point_left: | `:point_left:` |
| [top](#table-of-contents) | :point_right: | `:point_right:`  |  :raised_hands: | `:raised_hands:` |
| [top](#table-of-contents) | :pray: | `:pray:`  |  :point_up_2: | `:point_up_2:` |
| [top](#table-of-contents) | :clap: | `:clap:`  |  :muscle: | `:muscle:` |
| [top](#table-of-contents) | :metal: | `:metal:`  |  :fu: | `:fu:` |
| [top](#table-of-contents) | :runner: | `:runner:`  |  :running: | `:running:` |
| [top](#table-of-contents) | :couple: | `:couple:`  |  :family: | `:family:` |
| [top](#table-of-contents) | :two_men_holding_hands: | `:two_men_holding_hands:`  |  :two_women_holding_hands: | `:two_women_holding_hands:` |
| [top](#table-of-contents) | :dancer: | `:dancer:`  |  :dancers: | `:dancers:` |
| [top](#table-of-contents) | :ok_woman: | `:ok_woman:`  |  :no_good: | `:no_good:` |
| [top](#table-of-contents) | :information_desk_person: | `:information_desk_person:`  |  :raising_hand: | `:raising_hand:` |
| [top](#table-of-contents) | :bride_with_veil: | `:bride_with_veil:`  |  :person_with_pouting_face: | `:person_with_pouting_face:` |
| [top](#table-of-contents) | :person_frowning: | `:person_frowning:`  |  :bow: | `:bow:` |
| [top](#table-of-contents) | :couple_with_heart: | `:couple_with_heart:`  |  :massage: | `:massage:` |
| [top](#table-of-contents) | :haircut: | `:haircut:`  |  :nail_care: | `:nail_care:` |
| [top](#table-of-contents) | :boy: | `:boy:`  |  :girl: | `:girl:` |
| [top](#table-of-contents) | :woman: | `:woman:`  |  :man: | `:man:` |
| [top](#table-of-contents) | :baby: | `:baby:`  |  :older_woman: | `:older_woman:` |
| [top](#table-of-contents) | :older_man: | `:older_man:`  |  :person_with_blond_hair: | `:person_with_blond_hair:` |
| [top](#table-of-contents) | :man_with_gua_pi_mao: | `:man_with_gua_pi_mao:`  |  :man_with_turban: | `:man_with_turban:` |
| [top](#table-of-contents) | :construction_worker: | `:construction_worker:`  |  :cop: | `:cop:` |
| [top](#table-of-contents) | :angel: | `:angel:`  |  :princess: | `:princess:` |
| [top](#table-of-contents) | :smiley_cat: | `:smiley_cat:`  |  :smile_cat: | `:smile_cat:` |
| [top](#table-of-contents) | :heart_eyes_cat: | `:heart_eyes_cat:`  |  :kissing_cat: | `:kissing_cat:` |
| [top](#table-of-contents) | :smirk_cat: | `:smirk_cat:`  |  :scream_cat: | `:scream_cat:` |
| [top](#table-of-contents) | :crying_cat_face: | `:crying_cat_face:`  |  :joy_cat: | `:joy_cat:` |
| [top](#table-of-contents) | :pouting_cat: | `:pouting_cat:`  |  :japanese_ogre: | `:japanese_ogre:` |
| [top](#table-of-contents) | :japanese_goblin: | `:japanese_goblin:`  |  :see_no_evil: | `:see_no_evil:` |
| [top](#table-of-contents) | :hear_no_evil: | `:hear_no_evil:`  |  :speak_no_evil: | `:speak_no_evil:` |
| [top](#table-of-contents) | :guardsman: | `:guardsman:`  |  :skull: | `:skull:` |
| [top](#table-of-contents) | :feet: | `:feet:`  |  :lips: | `:lips:` |
| [top](#table-of-contents) | :kiss: | `:kiss:`  |  :droplet: | `:droplet:` |
| [top](#table-of-contents) | :ear: | `:ear:`  |  :eyes: | `:eyes:` |
| [top](#table-of-contents) | :nose: | `:nose:`  |  :tongue: | `:tongue:` |
| [top](#table-of-contents) | :love_letter: | `:love_letter:`  |  :bust_in_silhouette: | `:bust_in_silhouette:` |
| [top](#table-of-contents) | :busts_in_silhouette: | `:busts_in_silhouette:`  |  :speech_balloon: | `:speech_balloon:` |
| [top](#table-of-contents) | :thought_balloon: | `:thought_balloon:`  |  :feelsgood: | `:feelsgood:` |
| [top](#table-of-contents) | :finnadie: | `:finnadie:`  |  :goberserk: | `:goberserk:` |
| [top](#table-of-contents) | :godmode: | `:godmode:`  |  :hurtrealbad: | `:hurtrealbad:` |
| [top](#table-of-contents) | :rage1: | `:rage1:`  |  :rage2: | `:rage2:` |
| [top](#table-of-contents) | :rage3: | `:rage3:`  |  :rage4: | `:rage4:` |
| [top](#table-of-contents) | :suspect: | `:suspect:`  |  :trollface: | `:trollface:` |

### Nature

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :sunny: | `:sunny:`  |  :umbrella: | `:umbrella:` |
| [top](#table-of-contents) | :cloud: | `:cloud:`  |  :snowflake: | `:snowflake:` |
| [top](#table-of-contents) | :snowman: | `:snowman:`  |  :zap: | `:zap:` |
| [top](#table-of-contents) | :cyclone: | `:cyclone:`  |  :foggy: | `:foggy:` |
| [top](#table-of-contents) | :ocean: | `:ocean:`  |  :cat: | `:cat:` |
| [top](#table-of-contents) | :dog: | `:dog:`  |  :mouse: | `:mouse:` |
| [top](#table-of-contents) | :hamster: | `:hamster:`  |  :rabbit: | `:rabbit:` |
| [top](#table-of-contents) | :wolf: | `:wolf:`  |  :frog: | `:frog:` |
| [top](#table-of-contents) | :tiger: | `:tiger:`  |  :koala: | `:koala:` |
| [top](#table-of-contents) | :bear: | `:bear:`  |  :pig: | `:pig:` |
| [top](#table-of-contents) | :pig_nose: | `:pig_nose:`  |  :cow: | `:cow:` |
| [top](#table-of-contents) | :boar: | `:boar:`  |  :monkey_face: | `:monkey_face:` |
| [top](#table-of-contents) | :monkey: | `:monkey:`  |  :horse: | `:horse:` |
| [top](#table-of-contents) | :racehorse: | `:racehorse:`  |  :camel: | `:camel:` |
| [top](#table-of-contents) | :sheep: | `:sheep:`  |  :elephant: | `:elephant:` |
| [top](#table-of-contents) | :panda_face: | `:panda_face:`  |  :snake: | `:snake:` |
| [top](#table-of-contents) | :bird: | `:bird:`  |  :baby_chick: | `:baby_chick:` |
| [top](#table-of-contents) | :hatched_chick: | `:hatched_chick:`  |  :hatching_chick: | `:hatching_chick:` |
| [top](#table-of-contents) | :chicken: | `:chicken:`  |  :penguin: | `:penguin:` |
| [top](#table-of-contents) | :turtle: | `:turtle:`  |  :bug: | `:bug:` |
| [top](#table-of-contents) | :honeybee: | `:honeybee:`  |  :ant: | `:ant:` |
| [top](#table-of-contents) | :beetle: | `:beetle:`  |  :snail: | `:snail:` |
| [top](#table-of-contents) | :octopus: | `:octopus:`  |  :tropical_fish: | `:tropical_fish:` |
| [top](#table-of-contents) | :fish: | `:fish:`  |  :whale: | `:whale:` |
| [top](#table-of-contents) | :whale2: | `:whale2:`  |  :dolphin: | `:dolphin:` |
| [top](#table-of-contents) | :cow2: | `:cow2:`  |  :ram: | `:ram:` |
| [top](#table-of-contents) | :rat: | `:rat:`  |  :water_buffalo: | `:water_buffalo:` |
| [top](#table-of-contents) | :tiger2: | `:tiger2:`  |  :rabbit2: | `:rabbit2:` |
| [top](#table-of-contents) | :dragon: | `:dragon:`  |  :goat: | `:goat:` |
| [top](#table-of-contents) | :rooster: | `:rooster:`  |  :dog2: | `:dog2:` |
| [top](#table-of-contents) | :pig2: | `:pig2:`  |  :mouse2: | `:mouse2:` |
| [top](#table-of-contents) | :ox: | `:ox:`  |  :dragon_face: | `:dragon_face:` |
| [top](#table-of-contents) | :blowfish: | `:blowfish:`  |  :crocodile: | `:crocodile:` |
| [top](#table-of-contents) | :dromedary_camel: | `:dromedary_camel:`  |  :leopard: | `:leopard:` |
| [top](#table-of-contents) | :cat2: | `:cat2:`  |  :poodle: | `:poodle:` |
| [top](#table-of-contents) | :paw_prints: | `:paw_prints:`  |  :bouquet: | `:bouquet:` |
| [top](#table-of-contents) | :cherry_blossom: | `:cherry_blossom:`  |  :tulip: | `:tulip:` |
| [top](#table-of-contents) | :four_leaf_clover: | `:four_leaf_clover:`  |  :rose: | `:rose:` |
| [top](#table-of-contents) | :sunflower: | `:sunflower:`  |  :hibiscus: | `:hibiscus:` |
| [top](#table-of-contents) | :maple_leaf: | `:maple_leaf:`  |  :leaves: | `:leaves:` |
| [top](#table-of-contents) | :fallen_leaf: | `:fallen_leaf:`  |  :herb: | `:herb:` |
| [top](#table-of-contents) | :mushroom: | `:mushroom:`  |  :cactus: | `:cactus:` |
| [top](#table-of-contents) | :palm_tree: | `:palm_tree:`  |  :evergreen_tree: | `:evergreen_tree:` |
| [top](#table-of-contents) | :deciduous_tree: | `:deciduous_tree:`  |  :chestnut: | `:chestnut:` |
| [top](#table-of-contents) | :seedling: | `:seedling:`  |  :blossom: | `:blossom:` |
| [top](#table-of-contents) | :ear_of_rice: | `:ear_of_rice:`  |  :shell: | `:shell:` |
| [top](#table-of-contents) | :globe_with_meridians: | `:globe_with_meridians:`  |  :sun_with_face: | `:sun_with_face:` |
| [top](#table-of-contents) | :full_moon_with_face: | `:full_moon_with_face:`  |  :new_moon_with_face: | `:new_moon_with_face:` |
| [top](#table-of-contents) | :new_moon: | `:new_moon:`  |  :waxing_crescent_moon: | `:waxing_crescent_moon:` |
| [top](#table-of-contents) | :first_quarter_moon: | `:first_quarter_moon:`  |  :waxing_gibbous_moon: | `:waxing_gibbous_moon:` |
| [top](#table-of-contents) | :full_moon: | `:full_moon:`  |  :waning_gibbous_moon: | `:waning_gibbous_moon:` |
| [top](#table-of-contents) | :last_quarter_moon: | `:last_quarter_moon:`  |  :waning_crescent_moon: | `:waning_crescent_moon:` |
| [top](#table-of-contents) | :last_quarter_moon_with_face: | `:last_quarter_moon_with_face:`  |  :first_quarter_moon_with_face: | `:first_quarter_moon_with_face:` |
| [top](#table-of-contents) | :crescent_moon: | `:crescent_moon:`  |  :earth_africa: | `:earth_africa:` |
| [top](#table-of-contents) | :earth_americas: | `:earth_americas:`  |  :earth_asia: | `:earth_asia:` |
| [top](#table-of-contents) | :volcano: | `:volcano:`  |  :milky_way: | `:milky_way:` |
| [top](#table-of-contents) | :partly_sunny: | `:partly_sunny:`  |  :octocat: | `:octocat:` |
| [top](#table-of-contents) | :squirrel: | `:squirrel:`  |  | |

### Objects

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :bamboo: | `:bamboo:`  |  :gift_heart: | `:gift_heart:` |
| [top](#table-of-contents) | :dolls: | `:dolls:`  |  :school_satchel: | `:school_satchel:` |
| [top](#table-of-contents) | :mortar_board: | `:mortar_board:`  |  :flags: | `:flags:` |
| [top](#table-of-contents) | :fireworks: | `:fireworks:`  |  :sparkler: | `:sparkler:` |
| [top](#table-of-contents) | :wind_chime: | `:wind_chime:`  |  :rice_scene: | `:rice_scene:` |
| [top](#table-of-contents) | :jack_o_lantern: | `:jack_o_lantern:`  |  :ghost: | `:ghost:` |
| [top](#table-of-contents) | :santa: | `:santa:`  |  :christmas_tree: | `:christmas_tree:` |
| [top](#table-of-contents) | :gift: | `:gift:`  |  :bell: | `:bell:` |
| [top](#table-of-contents) | :no_bell: | `:no_bell:`  |  :tanabata_tree: | `:tanabata_tree:` |
| [top](#table-of-contents) | :tada: | `:tada:`  |  :confetti_ball: | `:confetti_ball:` |
| [top](#table-of-contents) | :balloon: | `:balloon:`  |  :crystal_ball: | `:crystal_ball:` |
| [top](#table-of-contents) | :cd: | `:cd:`  |  :dvd: | `:dvd:` |
| [top](#table-of-contents) | :floppy_disk: | `:floppy_disk:`  |  :camera: | `:camera:` |
| [top](#table-of-contents) | :video_camera: | `:video_camera:`  |  :movie_camera: | `:movie_camera:` |
| [top](#table-of-contents) | :computer: | `:computer:`  |  :tv: | `:tv:` |
| [top](#table-of-contents) | :iphone: | `:iphone:`  |  :phone: | `:phone:` |
| [top](#table-of-contents) | :telephone: | `:telephone:`  |  :telephone_receiver: | `:telephone_receiver:` |
| [top](#table-of-contents) | :pager: | `:pager:`  |  :fax: | `:fax:` |
| [top](#table-of-contents) | :minidisc: | `:minidisc:`  |  :vhs: | `:vhs:` |
| [top](#table-of-contents) | :sound: | `:sound:`  |  :speaker: | `:speaker:` |
| [top](#table-of-contents) | :mute: | `:mute:`  |  :loudspeaker: | `:loudspeaker:` |
| [top](#table-of-contents) | :mega: | `:mega:`  |  :hourglass: | `:hourglass:` |
| [top](#table-of-contents) | :hourglass_flowing_sand: | `:hourglass_flowing_sand:`  |  :alarm_clock: | `:alarm_clock:` |
| [top](#table-of-contents) | :watch: | `:watch:`  |  :radio: | `:radio:` |
| [top](#table-of-contents) | :satellite: | `:satellite:`  |  :loop: | `:loop:` |
| [top](#table-of-contents) | :mag: | `:mag:`  |  :mag_right: | `:mag_right:` |
| [top](#table-of-contents) | :unlock: | `:unlock:`  |  :lock: | `:lock:` |
| [top](#table-of-contents) | :lock_with_ink_pen: | `:lock_with_ink_pen:`  |  :closed_lock_with_key: | `:closed_lock_with_key:` |
| [top](#table-of-contents) | :key: | `:key:`  |  :bulb: | `:bulb:` |
| [top](#table-of-contents) | :flashlight: | `:flashlight:`  |  :high_brightness: | `:high_brightness:` |
| [top](#table-of-contents) | :low_brightness: | `:low_brightness:`  |  :electric_plug: | `:electric_plug:` |
| [top](#table-of-contents) | :battery: | `:battery:`  |  :calling: | `:calling:` |
| [top](#table-of-contents) | :email: | `:email:`  |  :mailbox: | `:mailbox:` |
| [top](#table-of-contents) | :postbox: | `:postbox:`  |  :bath: | `:bath:` |
| [top](#table-of-contents) | :bathtub: | `:bathtub:`  |  :shower: | `:shower:` |
| [top](#table-of-contents) | :toilet: | `:toilet:`  |  :wrench: | `:wrench:` |
| [top](#table-of-contents) | :nut_and_bolt: | `:nut_and_bolt:`  |  :hammer: | `:hammer:` |
| [top](#table-of-contents) | :seat: | `:seat:`  |  :moneybag: | `:moneybag:` |
| [top](#table-of-contents) | :yen: | `:yen:`  |  :dollar: | `:dollar:` |
| [top](#table-of-contents) | :pound: | `:pound:`  |  :euro: | `:euro:` |
| [top](#table-of-contents) | :credit_card: | `:credit_card:`  |  :money_with_wings: | `:money_with_wings:` |
| [top](#table-of-contents) | :e-mail: | `:e-mail:`  |  :inbox_tray: | `:inbox_tray:` |
| [top](#table-of-contents) | :outbox_tray: | `:outbox_tray:`  |  :envelope: | `:envelope:` |
| [top](#table-of-contents) | :incoming_envelope: | `:incoming_envelope:`  |  :postal_horn: | `:postal_horn:` |
| [top](#table-of-contents) | :mailbox_closed: | `:mailbox_closed:`  |  :mailbox_with_mail: | `:mailbox_with_mail:` |
| [top](#table-of-contents) | :mailbox_with_no_mail: | `:mailbox_with_no_mail:`  |  :package: | `:package:` |
| [top](#table-of-contents) | :door: | `:door:`  |  :smoking: | `:smoking:` |
| [top](#table-of-contents) | :bomb: | `:bomb:`  |  :gun: | `:gun:` |
| [top](#table-of-contents) | :hocho: | `:hocho:`  |  :pill: | `:pill:` |
| [top](#table-of-contents) | :syringe: | `:syringe:`  |  :page_facing_up: | `:page_facing_up:` |
| [top](#table-of-contents) | :page_with_curl: | `:page_with_curl:`  |  :bookmark_tabs: | `:bookmark_tabs:` |
| [top](#table-of-contents) | :bar_chart: | `:bar_chart:`  |  :chart_with_upwards_trend: | `:chart_with_upwards_trend:` |
| [top](#table-of-contents) | :chart_with_downwards_trend: | `:chart_with_downwards_trend:`  |  :scroll: | `:scroll:` |
| [top](#table-of-contents) | :clipboard: | `:clipboard:`  |  :calendar: | `:calendar:` |
| [top](#table-of-contents) | :date: | `:date:`  |  :card_index: | `:card_index:` |
| [top](#table-of-contents) | :file_folder: | `:file_folder:`  |  :open_file_folder: | `:open_file_folder:` |
| [top](#table-of-contents) | :scissors: | `:scissors:`  |  :pushpin: | `:pushpin:` |
| [top](#table-of-contents) | :paperclip: | `:paperclip:`  |  :black_nib: | `:black_nib:` |
| [top](#table-of-contents) | :pencil2: | `:pencil2:`  |  :straight_ruler: | `:straight_ruler:` |
| [top](#table-of-contents) | :triangular_ruler: | `:triangular_ruler:`  |  :closed_book: | `:closed_book:` |
| [top](#table-of-contents) | :green_book: | `:green_book:`  |  :blue_book: | `:blue_book:` |
| [top](#table-of-contents) | :orange_book: | `:orange_book:`  |  :notebook: | `:notebook:` |
| [top](#table-of-contents) | :notebook_with_decorative_cover: | `:notebook_with_decorative_cover:`  |  :ledger: | `:ledger:` |
| [top](#table-of-contents) | :books: | `:books:`  |  :bookmark: | `:bookmark:` |
| [top](#table-of-contents) | :name_badge: | `:name_badge:`  |  :microscope: | `:microscope:` |
| [top](#table-of-contents) | :telescope: | `:telescope:`  |  :newspaper: | `:newspaper:` |
| [top](#table-of-contents) | :football: | `:football:`  |  :basketball: | `:basketball:` |
| [top](#table-of-contents) | :soccer: | `:soccer:`  |  :baseball: | `:baseball:` |
| [top](#table-of-contents) | :tennis: | `:tennis:`  |  :8ball: | `:8ball:` |
| [top](#table-of-contents) | :rugby_football: | `:rugby_football:`  |  :bowling: | `:bowling:` |
| [top](#table-of-contents) | :golf: | `:golf:`  |  :mountain_bicyclist: | `:mountain_bicyclist:` |
| [top](#table-of-contents) | :bicyclist: | `:bicyclist:`  |  :horse_racing: | `:horse_racing:` |
| [top](#table-of-contents) | :snowboarder: | `:snowboarder:`  |  :swimmer: | `:swimmer:` |
| [top](#table-of-contents) | :surfer: | `:surfer:`  |  :ski: | `:ski:` |
| [top](#table-of-contents) | :spades: | `:spades:`  |  :hearts: | `:hearts:` |
| [top](#table-of-contents) | :clubs: | `:clubs:`  |  :diamonds: | `:diamonds:` |
| [top](#table-of-contents) | :gem: | `:gem:`  |  :ring: | `:ring:` |
| [top](#table-of-contents) | :trophy: | `:trophy:`  |  :musical_score: | `:musical_score:` |
| [top](#table-of-contents) | :musical_keyboard: | `:musical_keyboard:`  |  :violin: | `:violin:` |
| [top](#table-of-contents) | :space_invader: | `:space_invader:`  |  :video_game: | `:video_game:` |
| [top](#table-of-contents) | :black_joker: | `:black_joker:`  |  :flower_playing_cards: | `:flower_playing_cards:` |
| [top](#table-of-contents) | :game_die: | `:game_die:`  |  :dart: | `:dart:` |
| [top](#table-of-contents) | :mahjong: | `:mahjong:`  |  :clapper: | `:clapper:` |
| [top](#table-of-contents) | :memo: | `:memo:`  |  :pencil: | `:pencil:` |
| [top](#table-of-contents) | :book: | `:book:`  |  :art: | `:art:` |
| [top](#table-of-contents) | :microphone: | `:microphone:`  |  :headphones: | `:headphones:` |
| [top](#table-of-contents) | :trumpet: | `:trumpet:`  |  :saxophone: | `:saxophone:` |
| [top](#table-of-contents) | :guitar: | `:guitar:`  |  :shoe: | `:shoe:` |
| [top](#table-of-contents) | :sandal: | `:sandal:`  |  :high_heel: | `:high_heel:` |
| [top](#table-of-contents) | :lipstick: | `:lipstick:`  |  :boot: | `:boot:` |
| [top](#table-of-contents) | :shirt: | `:shirt:`  |  :tshirt: | `:tshirt:` |
| [top](#table-of-contents) | :necktie: | `:necktie:`  |  :womans_clothes: | `:womans_clothes:` |
| [top](#table-of-contents) | :dress: | `:dress:`  |  :running_shirt_with_sash: | `:running_shirt_with_sash:` |
| [top](#table-of-contents) | :jeans: | `:jeans:`  |  :kimono: | `:kimono:` |
| [top](#table-of-contents) | :bikini: | `:bikini:`  |  :ribbon: | `:ribbon:` |
| [top](#table-of-contents) | :tophat: | `:tophat:`  |  :crown: | `:crown:` |
| [top](#table-of-contents) | :womans_hat: | `:womans_hat:`  |  :mans_shoe: | `:mans_shoe:` |
| [top](#table-of-contents) | :closed_umbrella: | `:closed_umbrella:`  |  :briefcase: | `:briefcase:` |
| [top](#table-of-contents) | :handbag: | `:handbag:`  |  :pouch: | `:pouch:` |
| [top](#table-of-contents) | :purse: | `:purse:`  |  :eyeglasses: | `:eyeglasses:` |
| [top](#table-of-contents) | :fishing_pole_and_fish: | `:fishing_pole_and_fish:`  |  :coffee: | `:coffee:` |
| [top](#table-of-contents) | :tea: | `:tea:`  |  :sake: | `:sake:` |
| [top](#table-of-contents) | :baby_bottle: | `:baby_bottle:`  |  :beer: | `:beer:` |
| [top](#table-of-contents) | :beers: | `:beers:`  |  :cocktail: | `:cocktail:` |
| [top](#table-of-contents) | :tropical_drink: | `:tropical_drink:`  |  :wine_glass: | `:wine_glass:` |
| [top](#table-of-contents) | :fork_and_knife: | `:fork_and_knife:`  |  :pizza: | `:pizza:` |
| [top](#table-of-contents) | :hamburger: | `:hamburger:`  |  :fries: | `:fries:` |
| [top](#table-of-contents) | :poultry_leg: | `:poultry_leg:`  |  :meat_on_bone: | `:meat_on_bone:` |
| [top](#table-of-contents) | :spaghetti: | `:spaghetti:`  |  :curry: | `:curry:` |
| [top](#table-of-contents) | :fried_shrimp: | `:fried_shrimp:`  |  :bento: | `:bento:` |
| [top](#table-of-contents) | :sushi: | `:sushi:`  |  :fish_cake: | `:fish_cake:` |
| [top](#table-of-contents) | :rice_ball: | `:rice_ball:`  |  :rice_cracker: | `:rice_cracker:` |
| [top](#table-of-contents) | :rice: | `:rice:`  |  :ramen: | `:ramen:` |
| [top](#table-of-contents) | :stew: | `:stew:`  |  :oden: | `:oden:` |
| [top](#table-of-contents) | :dango: | `:dango:`  |  :egg: | `:egg:` |
| [top](#table-of-contents) | :bread: | `:bread:`  |  :doughnut: | `:doughnut:` |
| [top](#table-of-contents) | :custard: | `:custard:`  |  :icecream: | `:icecream:` |
| [top](#table-of-contents) | :ice_cream: | `:ice_cream:`  |  :shaved_ice: | `:shaved_ice:` |
| [top](#table-of-contents) | :birthday: | `:birthday:`  |  :cake: | `:cake:` |
| [top](#table-of-contents) | :cookie: | `:cookie:`  |  :chocolate_bar: | `:chocolate_bar:` |
| [top](#table-of-contents) | :candy: | `:candy:`  |  :lollipop: | `:lollipop:` |
| [top](#table-of-contents) | :honey_pot: | `:honey_pot:`  |  :apple: | `:apple:` |
| [top](#table-of-contents) | :green_apple: | `:green_apple:`  |  :tangerine: | `:tangerine:` |
| [top](#table-of-contents) | :lemon: | `:lemon:`  |  :cherries: | `:cherries:` |
| [top](#table-of-contents) | :grapes: | `:grapes:`  |  :watermelon: | `:watermelon:` |
| [top](#table-of-contents) | :strawberry: | `:strawberry:`  |  :peach: | `:peach:` |
| [top](#table-of-contents) | :melon: | `:melon:`  |  :banana: | `:banana:` |
| [top](#table-of-contents) | :pear: | `:pear:`  |  :pineapple: | `:pineapple:` |
| [top](#table-of-contents) | :sweet_potato: | `:sweet_potato:`  |  :eggplant: | `:eggplant:` |
| [top](#table-of-contents) | :tomato: | `:tomato:`  |  :corn: | `:corn:` |

### Places

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :house: | `:house:`  |  :house_with_garden: | `:house_with_garden:` |
| [top](#table-of-contents) | :school: | `:school:`  |  :office: | `:office:` |
| [top](#table-of-contents) | :post_office: | `:post_office:`  |  :hospital: | `:hospital:` |
| [top](#table-of-contents) | :bank: | `:bank:`  |  :convenience_store: | `:convenience_store:` |
| [top](#table-of-contents) | :love_hotel: | `:love_hotel:`  |  :hotel: | `:hotel:` |
| [top](#table-of-contents) | :wedding: | `:wedding:`  |  :church: | `:church:` |
| [top](#table-of-contents) | :department_store: | `:department_store:`  |  :european_post_office: | `:european_post_office:` |
| [top](#table-of-contents) | :city_sunrise: | `:city_sunrise:`  |  :city_sunset: | `:city_sunset:` |
| [top](#table-of-contents) | :japanese_castle: | `:japanese_castle:`  |  :european_castle: | `:european_castle:` |
| [top](#table-of-contents) | :tent: | `:tent:`  |  :factory: | `:factory:` |
| [top](#table-of-contents) | :tokyo_tower: | `:tokyo_tower:`  |  :japan: | `:japan:` |
| [top](#table-of-contents) | :mount_fuji: | `:mount_fuji:`  |  :sunrise_over_mountains: | `:sunrise_over_mountains:` |
| [top](#table-of-contents) | :sunrise: | `:sunrise:`  |  :stars: | `:stars:` |
| [top](#table-of-contents) | :statue_of_liberty: | `:statue_of_liberty:`  |  :bridge_at_night: | `:bridge_at_night:` |
| [top](#table-of-contents) | :carousel_horse: | `:carousel_horse:`  |  :rainbow: | `:rainbow:` |
| [top](#table-of-contents) | :ferris_wheel: | `:ferris_wheel:`  |  :fountain: | `:fountain:` |
| [top](#table-of-contents) | :roller_coaster: | `:roller_coaster:`  |  :ship: | `:ship:` |
| [top](#table-of-contents) | :speedboat: | `:speedboat:`  |  :boat: | `:boat:` |
| [top](#table-of-contents) | :sailboat: | `:sailboat:`  |  :rowboat: | `:rowboat:` |
| [top](#table-of-contents) | :anchor: | `:anchor:`  |  :rocket: | `:rocket:` |
| [top](#table-of-contents) | :airplane: | `:airplane:`  |  :helicopter: | `:helicopter:` |
| [top](#table-of-contents) | :steam_locomotive: | `:steam_locomotive:`  |  :tram: | `:tram:` |
| [top](#table-of-contents) | :mountain_railway: | `:mountain_railway:`  |  :bike: | `:bike:` |
| [top](#table-of-contents) | :aerial_tramway: | `:aerial_tramway:`  |  :suspension_railway: | `:suspension_railway:` |
| [top](#table-of-contents) | :mountain_cableway: | `:mountain_cableway:`  |  :tractor: | `:tractor:` |
| [top](#table-of-contents) | :blue_car: | `:blue_car:`  |  :oncoming_automobile: | `:oncoming_automobile:` |
| [top](#table-of-contents) | :car: | `:car:`  |  :red_car: | `:red_car:` |
| [top](#table-of-contents) | :taxi: | `:taxi:`  |  :oncoming_taxi: | `:oncoming_taxi:` |
| [top](#table-of-contents) | :articulated_lorry: | `:articulated_lorry:`  |  :bus: | `:bus:` |
| [top](#table-of-contents) | :oncoming_bus: | `:oncoming_bus:`  |  :rotating_light: | `:rotating_light:` |
| [top](#table-of-contents) | :police_car: | `:police_car:`  |  :oncoming_police_car: | `:oncoming_police_car:` |
| [top](#table-of-contents) | :fire_engine: | `:fire_engine:`  |  :ambulance: | `:ambulance:` |
| [top](#table-of-contents) | :minibus: | `:minibus:`  |  :truck: | `:truck:` |
| [top](#table-of-contents) | :train: | `:train:`  |  :station: | `:station:` |
| [top](#table-of-contents) | :train2: | `:train2:`  |  :bullettrain_front: | `:bullettrain_front:` |
| [top](#table-of-contents) | :bullettrain_side: | `:bullettrain_side:`  |  :light_rail: | `:light_rail:` |
| [top](#table-of-contents) | :monorail: | `:monorail:`  |  :railway_car: | `:railway_car:` |
| [top](#table-of-contents) | :trolleybus: | `:trolleybus:`  |  :ticket: | `:ticket:` |
| [top](#table-of-contents) | :fuelpump: | `:fuelpump:`  |  :vertical_traffic_light: | `:vertical_traffic_light:` |
| [top](#table-of-contents) | :traffic_light: | `:traffic_light:`  |  :warning: | `:warning:` |
| [top](#table-of-contents) | :construction: | `:construction:`  |  :beginner: | `:beginner:` |
| [top](#table-of-contents) | :atm: | `:atm:`  |  :slot_machine: | `:slot_machine:` |
| [top](#table-of-contents) | :busstop: | `:busstop:`  |  :barber: | `:barber:` |
| [top](#table-of-contents) | :hotsprings: | `:hotsprings:`  |  :checkered_flag: | `:checkered_flag:` |
| [top](#table-of-contents) | :crossed_flags: | `:crossed_flags:`  |  :izakaya_lantern: | `:izakaya_lantern:` |
| [top](#table-of-contents) | :moyai: | `:moyai:`  |  :circus_tent: | `:circus_tent:` |
| [top](#table-of-contents) | :performing_arts: | `:performing_arts:`  |  :round_pushpin: | `:round_pushpin:` |
| [top](#table-of-contents) | :triangular_flag_on_post: | `:triangular_flag_on_post:`  |  :jp: | `:jp:` |
| [top](#table-of-contents) | :kr: | `:kr:`  |  :cn: | `:cn:` |
| [top](#table-of-contents) | :us: | `:us:`  |  :fr: | `:fr:` |
| [top](#table-of-contents) | :es: | `:es:`  |  :it: | `:it:` |
| [top](#table-of-contents) | :ru: | `:ru:`  |  :gb: | `:gb:` |
| [top](#table-of-contents) | :uk: | `:uk:`  |  :de: | `:de:` |

### Symbols

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :one: | `:one:`  |  :two: | `:two:` |
| [top](#table-of-contents) | :three: | `:three:`  |  :four: | `:four:` |
| [top](#table-of-contents) | :five: | `:five:`  |  :six: | `:six:` |
| [top](#table-of-contents) | :seven: | `:seven:`  |  :eight: | `:eight:` |
| [top](#table-of-contents) | :nine: | `:nine:`  |  :keycap_ten: | `:keycap_ten:` |
| [top](#table-of-contents) | :1234: | `:1234:`  |  :zero: | `:zero:` |
| [top](#table-of-contents) | :hash: | `:hash:`  |  :symbols: | `:symbols:` |
| [top](#table-of-contents) | :arrow_backward: | `:arrow_backward:`  |  :arrow_down: | `:arrow_down:` |
| [top](#table-of-contents) | :arrow_forward: | `:arrow_forward:`  |  :arrow_left: | `:arrow_left:` |
| [top](#table-of-contents) | :capital_abcd: | `:capital_abcd:`  |  :abcd: | `:abcd:` |
| [top](#table-of-contents) | :abc: | `:abc:`  |  :arrow_lower_left: | `:arrow_lower_left:` |
| [top](#table-of-contents) | :arrow_lower_right: | `:arrow_lower_right:`  |  :arrow_right: | `:arrow_right:` |
| [top](#table-of-contents) | :arrow_up: | `:arrow_up:`  |  :arrow_upper_left: | `:arrow_upper_left:` |
| [top](#table-of-contents) | :arrow_upper_right: | `:arrow_upper_right:`  |  :arrow_double_down: | `:arrow_double_down:` |
| [top](#table-of-contents) | :arrow_double_up: | `:arrow_double_up:`  |  :arrow_down_small: | `:arrow_down_small:` |
| [top](#table-of-contents) | :arrow_heading_down: | `:arrow_heading_down:`  |  :arrow_heading_up: | `:arrow_heading_up:` |
| [top](#table-of-contents) | :leftwards_arrow_with_hook: | `:leftwards_arrow_with_hook:`  |  :arrow_right_hook: | `:arrow_right_hook:` |
| [top](#table-of-contents) | :left_right_arrow: | `:left_right_arrow:`  |  :arrow_up_down: | `:arrow_up_down:` |
| [top](#table-of-contents) | :arrow_up_small: | `:arrow_up_small:`  |  :arrows_clockwise: | `:arrows_clockwise:` |
| [top](#table-of-contents) | :arrows_counterclockwise: | `:arrows_counterclockwise:`  |  :rewind: | `:rewind:` |
| [top](#table-of-contents) | :fast_forward: | `:fast_forward:`  |  :information_source: | `:information_source:` |
| [top](#table-of-contents) | :ok: | `:ok:`  |  :twisted_rightwards_arrows: | `:twisted_rightwards_arrows:` |
| [top](#table-of-contents) | :repeat: | `:repeat:`  |  :repeat_one: | `:repeat_one:` |
| [top](#table-of-contents) | :new: | `:new:`  |  :top: | `:top:` |
| [top](#table-of-contents) | :up: | `:up:`  |  :cool: | `:cool:` |
| [top](#table-of-contents) | :free: | `:free:`  |  :ng: | `:ng:` |
| [top](#table-of-contents) | :cinema: | `:cinema:`  |  :koko: | `:koko:` |
| [top](#table-of-contents) | :signal_strength: | `:signal_strength:`  |  :u5272: | `:u5272:` |
| [top](#table-of-contents) | :u5408: | `:u5408:`  |  :u55b6: | `:u55b6:` |
| [top](#table-of-contents) | :u6307: | `:u6307:`  |  :u6708: | `:u6708:` |
| [top](#table-of-contents) | :u6709: | `:u6709:`  |  :u6e80: | `:u6e80:` |
| [top](#table-of-contents) | :u7121: | `:u7121:`  |  :u7533: | `:u7533:` |
| [top](#table-of-contents) | :u7a7a: | `:u7a7a:`  |  :u7981: | `:u7981:` |
| [top](#table-of-contents) | :sa: | `:sa:`  |  :restroom: | `:restroom:` |
| [top](#table-of-contents) | :mens: | `:mens:`  |  :womens: | `:womens:` |
| [top](#table-of-contents) | :baby_symbol: | `:baby_symbol:`  |  :no_smoking: | `:no_smoking:` |
| [top](#table-of-contents) | :parking: | `:parking:`  |  :wheelchair: | `:wheelchair:` |
| [top](#table-of-contents) | :metro: | `:metro:`  |  :baggage_claim: | `:baggage_claim:` |
| [top](#table-of-contents) | :accept: | `:accept:`  |  :wc: | `:wc:` |
| [top](#table-of-contents) | :potable_water: | `:potable_water:`  |  :put_litter_in_its_place: | `:put_litter_in_its_place:` |
| [top](#table-of-contents) | :secret: | `:secret:`  |  :congratulations: | `:congratulations:` |
| [top](#table-of-contents) | :m: | `:m:`  |  :passport_control: | `:passport_control:` |
| [top](#table-of-contents) | :left_luggage: | `:left_luggage:`  |  :customs: | `:customs:` |
| [top](#table-of-contents) | :ideograph_advantage: | `:ideograph_advantage:`  |  :cl: | `:cl:` |
| [top](#table-of-contents) | :sos: | `:sos:`  |  :id: | `:id:` |
| [top](#table-of-contents) | :no_entry_sign: | `:no_entry_sign:`  |  :underage: | `:underage:` |
| [top](#table-of-contents) | :no_mobile_phones: | `:no_mobile_phones:`  |  :do_not_litter: | `:do_not_litter:` |
| [top](#table-of-contents) | :non-potable_water: | `:non-potable_water:`  |  :no_bicycles: | `:no_bicycles:` |
| [top](#table-of-contents) | :no_pedestrians: | `:no_pedestrians:`  |  :children_crossing: | `:children_crossing:` |
| [top](#table-of-contents) | :no_entry: | `:no_entry:`  |  :eight_spoked_asterisk: | `:eight_spoked_asterisk:` |
| [top](#table-of-contents) | :sparkle: | `:sparkle:`  |  :eight_pointed_black_star: | `:eight_pointed_black_star:` |
| [top](#table-of-contents) | :heart_decoration: | `:heart_decoration:`  |  :vs: | `:vs:` |
| [top](#table-of-contents) | :vibration_mode: | `:vibration_mode:`  |  :mobile_phone_off: | `:mobile_phone_off:` |
| [top](#table-of-contents) | :chart: | `:chart:`  |  :currency_exchange: | `:currency_exchange:` |
| [top](#table-of-contents) | :aries: | `:aries:`  |  :taurus: | `:taurus:` |
| [top](#table-of-contents) | :gemini: | `:gemini:`  |  :cancer: | `:cancer:` |
| [top](#table-of-contents) | :leo: | `:leo:`  |  :virgo: | `:virgo:` |
| [top](#table-of-contents) | :libra: | `:libra:`  |  :scorpius: | `:scorpius:` |
| [top](#table-of-contents) | :sagittarius: | `:sagittarius:`  |  :capricorn: | `:capricorn:` |
| [top](#table-of-contents) | :aquarius: | `:aquarius:`  |  :pisces: | `:pisces:` |
| [top](#table-of-contents) | :ophiuchus: | `:ophiuchus:`  |  :six_pointed_star: | `:six_pointed_star:` |
| [top](#table-of-contents) | :negative_squared_cross_mark: | `:negative_squared_cross_mark:`  |  :a: | `:a:` |
| [top](#table-of-contents) | :b: | `:b:`  |  :ab: | `:ab:` |
| [top](#table-of-contents) | :o2: | `:o2:`  |  :diamond_shape_with_a_dot_inside: | `:diamond_shape_with_a_dot_inside:` |
| [top](#table-of-contents) | :recycle: | `:recycle:`  |  :end: | `:end:` |
| [top](#table-of-contents) | :back: | `:back:`  |  :on: | `:on:` |
| [top](#table-of-contents) | :soon: | `:soon:`  |  :clock1: | `:clock1:` |
| [top](#table-of-contents) | :clock130: | `:clock130:`  |  :clock10: | `:clock10:` |
| [top](#table-of-contents) | :clock1030: | `:clock1030:`  |  :clock11: | `:clock11:` |
| [top](#table-of-contents) | :clock1130: | `:clock1130:`  |  :clock12: | `:clock12:` |
| [top](#table-of-contents) | :clock1230: | `:clock1230:`  |  :clock2: | `:clock2:` |
| [top](#table-of-contents) | :clock230: | `:clock230:`  |  :clock3: | `:clock3:` |
| [top](#table-of-contents) | :clock330: | `:clock330:`  |  :clock4: | `:clock4:` |
| [top](#table-of-contents) | :clock430: | `:clock430:`  |  :clock5: | `:clock5:` |
| [top](#table-of-contents) | :clock530: | `:clock530:`  |  :clock6: | `:clock6:` |
| [top](#table-of-contents) | :clock630: | `:clock630:`  |  :clock7: | `:clock7:` |
| [top](#table-of-contents) | :clock730: | `:clock730:`  |  :clock8: | `:clock8:` |
| [top](#table-of-contents) | :clock830: | `:clock830:`  |  :clock9: | `:clock9:` |
| [top](#table-of-contents) | :clock930: | `:clock930:`  |  :heavy_dollar_sign: | `:heavy_dollar_sign:` |
| [top](#table-of-contents) | :copyright: | `:copyright:`  |  :registered: | `:registered:` |
| [top](#table-of-contents) | :tm: | `:tm:`  |  :x: | `:x:` |
| [top](#table-of-contents) | :heavy_exclamation_mark: | `:heavy_exclamation_mark:`  |  :bangbang: | `:bangbang:` |
| [top](#table-of-contents) | :interrobang: | `:interrobang:`  |  :o: | `:o:` |
| [top](#table-of-contents) | :heavy_multiplication_x: | `:heavy_multiplication_x:`  |  :heavy_plus_sign: | `:heavy_plus_sign:` |
| [top](#table-of-contents) | :heavy_minus_sign: | `:heavy_minus_sign:`  |  :heavy_division_sign: | `:heavy_division_sign:` |
| [top](#table-of-contents) | :white_flower: | `:white_flower:`  |  :100: | `:100:` |
| [top](#table-of-contents) | :heavy_check_mark: | `:heavy_check_mark:`  |  :ballot_box_with_check: | `:ballot_box_with_check:` |
| [top](#table-of-contents) | :radio_button: | `:radio_button:`  |  :link: | `:link:` |
| [top](#table-of-contents) | :curly_loop: | `:curly_loop:`  |  :wavy_dash: | `:wavy_dash:` |
| [top](#table-of-contents) | :part_alternation_mark: | `:part_alternation_mark:`  |  :trident: | `:trident:` |
| [top](#table-of-contents) | :black_small_square: | `:black_small_square:`  |  :white_small_square: | `:white_small_square:` |
| [top](#table-of-contents) | :black_medium_small_square: | `:black_medium_small_square:`  |  :white_medium_small_square: | `:white_medium_small_square:` |
| [top](#table-of-contents) | :black_medium_square: | `:black_medium_square:`  |  :white_medium_square: | `:white_medium_square:` |
| [top](#table-of-contents) | :black_large_square: | `:black_large_square:`  |  :white_large_square: | `:white_large_square:` |
| [top](#table-of-contents) | :white_check_mark: | `:white_check_mark:`  |  :black_square_button: | `:black_square_button:` |
| [top](#table-of-contents) | :white_square_button: | `:white_square_button:`  |  :black_circle: | `:black_circle:` |
| [top](#table-of-contents) | :white_circle: | `:white_circle:`  |  :red_circle: | `:red_circle:` |
| [top](#table-of-contents) | :large_blue_circle: | `:large_blue_circle:`  |  :large_blue_diamond: | `:large_blue_diamond:` |
| [top](#table-of-contents) | :large_orange_diamond: | `:large_orange_diamond:`  |  :small_blue_diamond: | `:small_blue_diamond:` |
| [top](#table-of-contents) | :small_orange_diamond: | `:small_orange_diamond:`  |  :small_red_triangle: | `:small_red_triangle:` |
| [top](#table-of-contents) | :small_red_triangle_down: | `:small_red_triangle_down:`  |  :shipit: | `:shipit:` |

### Uncategorized

|   | ico | emoji | ico | emoji |
| - | --- | ----- | --- | ----- |
| [top](#table-of-contents) | :1st_place_medal: | `:1st_place_medal:`  |  :2nd_place_medal: | `:2nd_place_medal:` |
| [top](#table-of-contents) | :3rd_place_medal: | `:3rd_place_medal:`  |  :afghanistan: | `:afghanistan:` |
| [top](#table-of-contents) | :aland_islands: | `:aland_islands:`  |  :albania: | `:albania:` |
| [top](#table-of-contents) | :alembic: | `:alembic:`  |  :algeria: | `:algeria:` |
| [top](#table-of-contents) | :american_samoa: | `:american_samoa:`  |  :amphora: | `:amphora:` |
| [top](#table-of-contents) | :andorra: | `:andorra:`  |  :angola: | `:angola:` |
| [top](#table-of-contents) | :anguilla: | `:anguilla:`  |  :antarctica: | `:antarctica:` |
| [top](#table-of-contents) | :antigua_barbuda: | `:antigua_barbuda:`  |  :argentina: | `:argentina:` |
| [top](#table-of-contents) | :armenia: | `:armenia:`  |  :artificial_satellite: | `:artificial_satellite:` |
| [top](#table-of-contents) | :aruba: | `:aruba:`  |  :asterisk: | `:asterisk:` |
| [top](#table-of-contents) | :athletic_shoe: | `:athletic_shoe:`  |  :atom: | `:atom:` |
| [top](#table-of-contents) | :atom_symbol: | `:atom_symbol:`  |  :australia: | `:australia:` |
| [top](#table-of-contents) | :austria: | `:austria:`  |  :avocado: | `:avocado:` |
| [top](#table-of-contents) | :azerbaijan: | `:azerbaijan:`  |  :bacon: | `:bacon:` |
| [top](#table-of-contents) | :badminton: | `:badminton:`  |  :baguette_bread: | `:baguette_bread:` |
| [top](#table-of-contents) | :bahamas: | `:bahamas:`  |  :bahrain: | `:bahrain:` |
| [top](#table-of-contents) | :balance_scale: | `:balance_scale:`  |  :ballot_box: | `:ballot_box:` |
| [top](#table-of-contents) | :bangladesh: | `:bangladesh:`  |  :barbados: | `:barbados:` |
| [top](#table-of-contents) | :basecamp: | `:basecamp:`  |  :basecampy: | `:basecampy:` |
| [top](#table-of-contents) | :basketball_man: | `:basketball_man:`  |  :basketball_woman: | `:basketball_woman:` |
| [top](#table-of-contents) | :bat: | `:bat:`  |  :beach_umbrella: | `:beach_umbrella:` |
| [top](#table-of-contents) | :bed: | `:bed:`  |  :bee: | `:bee:` |
| [top](#table-of-contents) | :belarus: | `:belarus:`  |  :belgium: | `:belgium:` |
| [top](#table-of-contents) | :belize: | `:belize:`  |  :bellhop_bell: | `:bellhop_bell:` |
| [top](#table-of-contents) | :benin: | `:benin:`  |  :bermuda: | `:bermuda:` |
| [top](#table-of-contents) | :bhutan: | `:bhutan:`  |  :biking_man: | `:biking_man:` |
| [top](#table-of-contents) | :biking_woman: | `:biking_woman:`  |  :biohazard: | `:biohazard:` |
| [top](#table-of-contents) | :black_flag: | `:black_flag:`  |  :black_heart: | `:black_heart:` |
| [top](#table-of-contents) | :blonde_man: | `:blonde_man:`  |  :blonde_woman: | `:blonde_woman:` |
| [top](#table-of-contents) | :bolivia: | `:bolivia:`  |  :bosnia_herzegovina: | `:bosnia_herzegovina:` |
| [top](#table-of-contents) | :botswana: | `:botswana:`  |  :bow_and_arrow: | `:bow_and_arrow:` |
| [top](#table-of-contents) | :bowing_man: | `:bowing_man:`  |  :bowing_woman: | `:bowing_woman:` |
| [top](#table-of-contents) | :boxing_glove: | `:boxing_glove:`  |  :brazil: | `:brazil:` |
| [top](#table-of-contents) | :british_indian_ocean_territory: | `:british_indian_ocean_territory:`  |  :british_virgin_islands: | `:british_virgin_islands:` |
| [top](#table-of-contents) | :brunei: | `:brunei:`  |  :building_construction: | `:building_construction:` |
| [top](#table-of-contents) | :bulgaria: | `:bulgaria:`  |  :burkina_faso: | `:burkina_faso:` |
| [top](#table-of-contents) | :burrito: | `:burrito:`  |  :burundi: | `:burundi:` |
| [top](#table-of-contents) | :business_suit_levitating: | `:business_suit_levitating:`  |  :butterfly: | `:butterfly:` |
| [top](#table-of-contents) | :call_me_hand: | `:call_me_hand:`  |  :cambodia: | `:cambodia:` |
| [top](#table-of-contents) | :camera_flash: | `:camera_flash:`  |  :cameroon: | `:cameroon:` |
| [top](#table-of-contents) | :camping: | `:camping:`  |  :canada: | `:canada:` |
| [top](#table-of-contents) | :canary_islands: | `:canary_islands:`  |  :candle: | `:candle:` |
| [top](#table-of-contents) | :canoe: | `:canoe:`  |  :cape_verde: | `:cape_verde:` |
| [top](#table-of-contents) | :card_file_box: | `:card_file_box:`  |  :card_index_dividers: | `:card_index_dividers:` |
| [top](#table-of-contents) | :caribbean_netherlands: | `:caribbean_netherlands:`  |  :carrot: | `:carrot:` |
| [top](#table-of-contents) | :cayman_islands: | `:cayman_islands:`  |  :central_african_republic: | `:central_african_republic:` |
| [top](#table-of-contents) | :chad: | `:chad:`  |  :chains: | `:chains:` |
| [top](#table-of-contents) | :champagne: | `:champagne:`  |  :cheese: | `:cheese:` |
| [top](#table-of-contents) | :chile: | `:chile:`  |  :chipmunk: | `:chipmunk:` |
| [top](#table-of-contents) | :christmas_island: | `:christmas_island:`  |  :cityscape: | `:cityscape:` |
| [top](#table-of-contents) | :clamp: | `:clamp:`  |  :classical_building: | `:classical_building:` |
| [top](#table-of-contents) | :clinking_glasses: | `:clinking_glasses:`  |  :cloud_with_lightning: | `:cloud_with_lightning:` |
| [top](#table-of-contents) | :cloud_with_lightning_and_rain: | `:cloud_with_lightning_and_rain:`  |  :cloud_with_rain: | `:cloud_with_rain:` |
| [top](#table-of-contents) | :cloud_with_snow: | `:cloud_with_snow:`  |  :clown_face: | `:clown_face:` |
| [top](#table-of-contents) | :cocos_islands: | `:cocos_islands:`  |  :coffin: | `:coffin:` |
| [top](#table-of-contents) | :colombia: | `:colombia:`  |  :comet: | `:comet:` |
| [top](#table-of-contents) | :comoros: | `:comoros:`  |  :computer_mouse: | `:computer_mouse:` |
| [top](#table-of-contents) | :congo_brazzaville: | `:congo_brazzaville:`  |  :congo_kinshasa: | `:congo_kinshasa:` |
| [top](#table-of-contents) | :construction_worker_man: | `:construction_worker_man:`  |  :construction_worker_woman: | `:construction_worker_woman:` |
| [top](#table-of-contents) | :control_knobs: | `:control_knobs:`  |  :cook_islands: | `:cook_islands:` |
| [top](#table-of-contents) | :costa_rica: | `:costa_rica:`  |  :cote_divoire: | `:cote_divoire:` |
| [top](#table-of-contents) | :couch_and_lamp: | `:couch_and_lamp:`  |  :couple_with_heart_man_man: | `:couple_with_heart_man_man:` |
| [top](#table-of-contents) | :couple_with_heart_woman_man: | `:couple_with_heart_woman_man:`  |  :couple_with_heart_woman_woman: | `:couple_with_heart_woman_woman:` |
| [top](#table-of-contents) | :couplekiss_man_man: | `:couplekiss_man_man:`  |  :couplekiss_man_woman: | `:couplekiss_man_woman:` |
| [top](#table-of-contents) | :couplekiss_woman_woman: | `:couplekiss_woman_woman:`  |  :cowboy_hat_face: | `:cowboy_hat_face:` |
| [top](#table-of-contents) | :crab: | `:crab:`  |  :crayon: | `:crayon:` |
| [top](#table-of-contents) | :cricket: | `:cricket:`  |  :croatia: | `:croatia:` |
| [top](#table-of-contents) | :croissant: | `:croissant:`  |  :crossed_fingers: | `:crossed_fingers:` |
| [top](#table-of-contents) | :crossed_swords: | `:crossed_swords:`  |  :cuba: | `:cuba:` |
| [top](#table-of-contents) | :cucumber: | `:cucumber:`  |  :curacao: | `:curacao:` |
| [top](#table-of-contents) | :cyprus: | `:cyprus:`  |  :czech_republic: | `:czech_republic:` |
| [top](#table-of-contents) | :dagger: | `:dagger:`  |  :dancing_men: | `:dancing_men:` |
| [top](#table-of-contents) | :dancing_women: | `:dancing_women:`  |  :dark_sunglasses: | `:dark_sunglasses:` |
| [top](#table-of-contents) | :deer: | `:deer:`  |  :denmark: | `:denmark:` |
| [top](#table-of-contents) | :derelict_house: | `:derelict_house:`  |  :desert: | `:desert:` |
| [top](#table-of-contents) | :desert_island: | `:desert_island:`  |  :desktop_computer: | `:desktop_computer:` |
| [top](#table-of-contents) | :detective: | `:detective:`  |  :djibouti: | `:djibouti:` |
| [top](#table-of-contents) | :dominica: | `:dominica:`  |  :dominican_republic: | `:dominican_republic:` |
| [top](#table-of-contents) | :dove: | `:dove:`  |  :drooling_face: | `:drooling_face:` |
| [top](#table-of-contents) | :drum: | `:drum:`  |  :duck: | `:duck:` |
| [top](#table-of-contents) | :eagle: | `:eagle:`  |  :ecuador: | `:ecuador:` |
| [top](#table-of-contents) | :egypt: | `:egypt:`  |  :el_salvador: | `:el_salvador:` |
| [top](#table-of-contents) | :electron: | `:electron:`  |  :envelope_with_arrow: | `:envelope_with_arrow:` |
| [top](#table-of-contents) | :equatorial_guinea: | `:equatorial_guinea:`  |  :eritrea: | `:eritrea:` |
| [top](#table-of-contents) | :estonia: | `:estonia:`  |  :ethiopia: | `:ethiopia:` |
| [top](#table-of-contents) | :eu: | `:eu:`  |  :european_union: | `:european_union:` |
| [top](#table-of-contents) | :eye: | `:eye:`  |  :eye_speech_bubble: | `:eye_speech_bubble:` |
| [top](#table-of-contents) | :face_with_head_bandage: | `:face_with_head_bandage:`  |  :face_with_thermometer: | `:face_with_thermometer:` |
| [top](#table-of-contents) | :falkland_islands: | `:falkland_islands:`  |  :family_man_boy: | `:family_man_boy:` |
| [top](#table-of-contents) | :family_man_boy_boy: | `:family_man_boy_boy:`  |  :family_man_girl: | `:family_man_girl:` |
| [top](#table-of-contents) | :family_man_girl_boy: | `:family_man_girl_boy:`  |  :family_man_girl_girl: | `:family_man_girl_girl:` |
| [top](#table-of-contents) | :family_man_man_boy: | `:family_man_man_boy:`  |  :family_man_man_boy_boy: | `:family_man_man_boy_boy:` |
| [top](#table-of-contents) | :family_man_man_girl: | `:family_man_man_girl:`  |  :family_man_man_girl_boy: | `:family_man_man_girl_boy:` |
| [top](#table-of-contents) | :family_man_man_girl_girl: | `:family_man_man_girl_girl:`  |  :family_man_woman_boy: | `:family_man_woman_boy:` |
| [top](#table-of-contents) | :family_man_woman_boy_boy: | `:family_man_woman_boy_boy:`  |  :family_man_woman_girl: | `:family_man_woman_girl:` |
| [top](#table-of-contents) | :family_man_woman_girl_boy: | `:family_man_woman_girl_boy:`  |  :family_man_woman_girl_girl: | `:family_man_woman_girl_girl:` |
| [top](#table-of-contents) | :family_woman_boy: | `:family_woman_boy:`  |  :family_woman_boy_boy: | `:family_woman_boy_boy:` |
| [top](#table-of-contents) | :family_woman_girl: | `:family_woman_girl:`  |  :family_woman_girl_boy: | `:family_woman_girl_boy:` |
| [top](#table-of-contents) | :family_woman_girl_girl: | `:family_woman_girl_girl:`  |  :family_woman_woman_boy: | `:family_woman_woman_boy:` |
| [top](#table-of-contents) | :family_woman_woman_boy_boy: | `:family_woman_woman_boy_boy:`  |  :family_woman_woman_girl: | `:family_woman_woman_girl:` |
| [top](#table-of-contents) | :family_woman_woman_girl_boy: | `:family_woman_woman_girl_boy:`  |  :family_woman_woman_girl_girl: | `:family_woman_woman_girl_girl:` |
| [top](#table-of-contents) | :faroe_islands: | `:faroe_islands:`  |  :female_detective: | `:female_detective:` |
| [top](#table-of-contents) | :ferry: | `:ferry:`  |  :field_hockey: | `:field_hockey:` |
| [top](#table-of-contents) | :fiji: | `:fiji:`  |  :file_cabinet: | `:file_cabinet:` |
| [top](#table-of-contents) | :film_projector: | `:film_projector:`  |  :film_strip: | `:film_strip:` |
| [top](#table-of-contents) | :finland: | `:finland:`  |  :fist_left: | `:fist_left:` |
| [top](#table-of-contents) | :fist_oncoming: | `:fist_oncoming:`  |  :fist_raised: | `:fist_raised:` |
| [top](#table-of-contents) | :fist_right: | `:fist_right:`  |  :fleur_de_lis: | `:fleur_de_lis:` |
| [top](#table-of-contents) | :flight_arrival: | `:flight_arrival:`  |  :flight_departure: | `:flight_departure:` |
| [top](#table-of-contents) | :flipper: | `:flipper:`  |  :fog: | `:fog:` |
| [top](#table-of-contents) | :footprints: | `:footprints:`  |  :fountain_pen: | `:fountain_pen:` |
| [top](#table-of-contents) | :fox_face: | `:fox_face:`  |  :framed_picture: | `:framed_picture:` |
| [top](#table-of-contents) | :french_guiana: | `:french_guiana:`  |  :french_polynesia: | `:french_polynesia:` |
| [top](#table-of-contents) | :french_southern_territories: | `:french_southern_territories:`  |  :fried_egg: | `:fried_egg:` |
| [top](#table-of-contents) | :frowning_face: | `:frowning_face:`  |  :frowning_man: | `:frowning_man:` |
| [top](#table-of-contents) | :frowning_woman: | `:frowning_woman:`  |  :funeral_urn: | `:funeral_urn:` |
| [top](#table-of-contents) | :gabon: | `:gabon:`  |  :gambia: | `:gambia:` |
| [top](#table-of-contents) | :gear: | `:gear:`  |  :georgia: | `:georgia:` |
| [top](#table-of-contents) | :ghana: | `:ghana:`  |  :gibraltar: | `:gibraltar:` |
| [top](#table-of-contents) | :goal_net: | `:goal_net:`  |  :golfing_man: | `:golfing_man:` |
| [top](#table-of-contents) | :golfing_woman: | `:golfing_woman:`  |  :gorilla: | `:gorilla:` |
| [top](#table-of-contents) | :greece: | `:greece:`  |  :green_salad: | `:green_salad:` |
| [top](#table-of-contents) | :greenland: | `:greenland:`  |  :grenada: | `:grenada:` |
| [top](#table-of-contents) | :guadeloupe: | `:guadeloupe:`  |  :guam: | `:guam:` |
| [top](#table-of-contents) | :guardswoman: | `:guardswoman:`  |  :guatemala: | `:guatemala:` |
| [top](#table-of-contents) | :guernsey: | `:guernsey:`  |  :guinea: | `:guinea:` |
| [top](#table-of-contents) | :guinea_bissau: | `:guinea_bissau:`  |  :guyana: | `:guyana:` |
| [top](#table-of-contents) | :haircut_man: | `:haircut_man:`  |  :haircut_woman: | `:haircut_woman:` |
| [top](#table-of-contents) | :haiti: | `:haiti:`  |  :hammer_and_pick: | `:hammer_and_pick:` |
| [top](#table-of-contents) | :hammer_and_wrench: | `:hammer_and_wrench:`  |  :handshake: | `:handshake:` |
| [top](#table-of-contents) | :heavy_heart_exclamation: | `:heavy_heart_exclamation:`  |  :hole: | `:hole:` |
| [top](#table-of-contents) | :honduras: | `:honduras:`  |  :hong_kong: | `:hong_kong:` |
| [top](#table-of-contents) | :hot_pepper: | `:hot_pepper:`  |  :hotdog: | `:hotdog:` |
| [top](#table-of-contents) | :houses: | `:houses:`  |  :hugs: | `:hugs:` |
| [top](#table-of-contents) | :hungary: | `:hungary:`  |  :ice_hockey: | `:ice_hockey:` |
| [top](#table-of-contents) | :ice_skate: | `:ice_skate:`  |  :iceland: | `:iceland:` |
| [top](#table-of-contents) | :india: | `:india:`  |  :indonesia: | `:indonesia:` |
| [top](#table-of-contents) | :iran: | `:iran:`  |  :iraq: | `:iraq:` |
| [top](#table-of-contents) | :ireland: | `:ireland:`  |  :isle_of_man: | `:isle_of_man:` |
| [top](#table-of-contents) | :israel: | `:israel:`  |  :jamaica: | `:jamaica:` |
| [top](#table-of-contents) | :jersey: | `:jersey:`  |  :jordan: | `:jordan:` |
| [top](#table-of-contents) | :joystick: | `:joystick:`  |  :kaaba: | `:kaaba:` |
| [top](#table-of-contents) | :kazakhstan: | `:kazakhstan:`  |  :kenya: | `:kenya:` |
| [top](#table-of-contents) | :keyboard: | `:keyboard:`  |  :kick_scooter: | `:kick_scooter:` |
| [top](#table-of-contents) | :kiribati: | `:kiribati:`  |  :kiwi_fruit: | `:kiwi_fruit:` |
| [top](#table-of-contents) | :knife: | `:knife:`  |  :kosovo: | `:kosovo:` |
| [top](#table-of-contents) | :kuwait: | `:kuwait:`  |  :kyrgyzstan: | `:kyrgyzstan:` |
| [top](#table-of-contents) | :label: | `:label:`  |  :lantern: | `:lantern:` |
| [top](#table-of-contents) | :laos: | `:laos:`  |  :latin_cross: | `:latin_cross:` |
| [top](#table-of-contents) | :latvia: | `:latvia:`  |  :lebanon: | `:lebanon:` |
| [top](#table-of-contents) | :lesotho: | `:lesotho:`  |  :level_slider: | `:level_slider:` |
| [top](#table-of-contents) | :liberia: | `:liberia:`  |  :libya: | `:libya:` |
| [top](#table-of-contents) | :liechtenstein: | `:liechtenstein:`  |  :lion: | `:lion:` |
| [top](#table-of-contents) | :lithuania: | `:lithuania:`  |  :lizard: | `:lizard:` |
| [top](#table-of-contents) | :loud_sound: | `:loud_sound:`  |  :luxembourg: | `:luxembourg:` |
| [top](#table-of-contents) | :lying_face: | `:lying_face:`  |  :macau: | `:macau:` |
| [top](#table-of-contents) | :macedonia: | `:macedonia:`  |  :madagascar: | `:madagascar:` |
| [top](#table-of-contents) | :malawi: | `:malawi:`  |  :malaysia: | `:malaysia:` |
| [top](#table-of-contents) | :maldives: | `:maldives:`  |  :male_detective: | `:male_detective:` |
| [top](#table-of-contents) | :mali: | `:mali:`  |  :malta: | `:malta:` |
| [top](#table-of-contents) | :man_artist: | `:man_artist:`  |  :man_astronaut: | `:man_astronaut:` |
| [top](#table-of-contents) | :man_cartwheeling: | `:man_cartwheeling:`  |  :man_cook: | `:man_cook:` |
| [top](#table-of-contents) | :man_dancing: | `:man_dancing:`  |  :man_facepalming: | `:man_facepalming:` |
| [top](#table-of-contents) | :man_factory_worker: | `:man_factory_worker:`  |  :man_farmer: | `:man_farmer:` |
| [top](#table-of-contents) | :man_firefighter: | `:man_firefighter:`  |  :man_health_worker: | `:man_health_worker:` |
| [top](#table-of-contents) | :man_in_tuxedo: | `:man_in_tuxedo:`  |  :man_judge: | `:man_judge:` |
| [top](#table-of-contents) | :man_juggling: | `:man_juggling:`  |  :man_mechanic: | `:man_mechanic:` |
| [top](#table-of-contents) | :man_office_worker: | `:man_office_worker:`  |  :man_pilot: | `:man_pilot:` |
| [top](#table-of-contents) | :man_playing_handball: | `:man_playing_handball:`  |  :man_playing_water_polo: | `:man_playing_water_polo:` |
| [top](#table-of-contents) | :man_scientist: | `:man_scientist:`  |  :man_shrugging: | `:man_shrugging:` |
| [top](#table-of-contents) | :man_singer: | `:man_singer:`  |  :man_student: | `:man_student:` |
| [top](#table-of-contents) | :man_teacher: | `:man_teacher:`  |  :man_technologist: | `:man_technologist:` |
| [top](#table-of-contents) | :mandarin: | `:mandarin:`  |  :mantelpiece_clock: | `:mantelpiece_clock:` |
| [top](#table-of-contents) | :marshall_islands: | `:marshall_islands:`  |  :martial_arts_uniform: | `:martial_arts_uniform:` |
| [top](#table-of-contents) | :martinique: | `:martinique:`  |  :massage_man: | `:massage_man:` |
| [top](#table-of-contents) | :massage_woman: | `:massage_woman:`  |  :mauritania: | `:mauritania:` |
| [top](#table-of-contents) | :mauritius: | `:mauritius:`  |  :mayotte: | `:mayotte:` |
| [top](#table-of-contents) | :medal_military: | `:medal_military:`  |  :medal_sports: | `:medal_sports:` |
| [top](#table-of-contents) | :men_wrestling: | `:men_wrestling:`  |  :menorah: | `:menorah:` |
| [top](#table-of-contents) | :mexico: | `:mexico:`  |  :micronesia: | `:micronesia:` |
| [top](#table-of-contents) | :middle_finger: | `:middle_finger:`  |  :milk_glass: | `:milk_glass:` |
| [top](#table-of-contents) | :moldova: | `:moldova:`  |  :monaco: | `:monaco:` |
| [top](#table-of-contents) | :money_mouth_face: | `:money_mouth_face:`  |  :mongolia: | `:mongolia:` |
| [top](#table-of-contents) | :montenegro: | `:montenegro:`  |  :montserrat: | `:montserrat:` |
| [top](#table-of-contents) | :moon: | `:moon:`  |  :morocco: | `:morocco:` |
| [top](#table-of-contents) | :mosque: | `:mosque:`  |  :motor_boat: | `:motor_boat:` |
| [top](#table-of-contents) | :motor_scooter: | `:motor_scooter:`  |  :motorcycle: | `:motorcycle:` |
| [top](#table-of-contents) | :motorway: | `:motorway:`  |  :mountain: | `:mountain:` |
| [top](#table-of-contents) | :mountain_biking_man: | `:mountain_biking_man:`  |  :mountain_biking_woman: | `:mountain_biking_woman:` |
| [top](#table-of-contents) | :mountain_snow: | `:mountain_snow:`  |  :mozambique: | `:mozambique:` |
| [top](#table-of-contents) | :mrs_claus: | `:mrs_claus:`  |  :myanmar: | `:myanmar:` |
| [top](#table-of-contents) | :namibia: | `:namibia:`  |  :national_park: | `:national_park:` |
| [top](#table-of-contents) | :nauru: | `:nauru:`  |  :nauseated_face: | `:nauseated_face:` |
| [top](#table-of-contents) | :nepal: | `:nepal:`  |  :nerd_face: | `:nerd_face:` |
| [top](#table-of-contents) | :netherlands: | `:netherlands:`  |  :new_caledonia: | `:new_caledonia:` |
| [top](#table-of-contents) | :new_zealand: | `:new_zealand:`  |  :newspaper_roll: | `:newspaper_roll:` |
| [top](#table-of-contents) | :next_track_button: | `:next_track_button:`  |  :ng_man: | `:ng_man:` |
| [top](#table-of-contents) | :ng_woman: | `:ng_woman:`  |  :nicaragua: | `:nicaragua:` |
| [top](#table-of-contents) | :niger: | `:niger:`  |  :nigeria: | `:nigeria:` |
| [top](#table-of-contents) | :night_with_stars: | `:night_with_stars:`  |  :niue: | `:niue:` |
| [top](#table-of-contents) | :no_good_man: | `:no_good_man:`  |  :no_good_woman: | `:no_good_woman:` |
| [top](#table-of-contents) | :norfolk_island: | `:norfolk_island:`  |  :north_korea: | `:north_korea:` |
| [top](#table-of-contents) | :northern_mariana_islands: | `:northern_mariana_islands:`  |  :norway: | `:norway:` |
| [top](#table-of-contents) | :oil_drum: | `:oil_drum:`  |  :ok_man: | `:ok_man:` |
| [top](#table-of-contents) | :old_key: | `:old_key:`  |  :om: | `:om:` |
| [top](#table-of-contents) | :oman: | `:oman:`  |  :open_book: | `:open_book:` |
| [top](#table-of-contents) | :open_umbrella: | `:open_umbrella:`  |  :orange: | `:orange:` |
| [top](#table-of-contents) | :orthodox_cross: | `:orthodox_cross:`  |  :owl: | `:owl:` |
| [top](#table-of-contents) | :paintbrush: | `:paintbrush:`  |  :pakistan: | `:pakistan:` |
| [top](#table-of-contents) | :palau: | `:palau:`  |  :palestinian_territories: | `:palestinian_territories:` |
| [top](#table-of-contents) | :panama: | `:panama:`  |  :pancakes: | `:pancakes:` |
| [top](#table-of-contents) | :paperclips: | `:paperclips:`  |  :papua_new_guinea: | `:papua_new_guinea:` |
| [top](#table-of-contents) | :paraguay: | `:paraguay:`  |  :parasol_on_ground: | `:parasol_on_ground:` |
| [top](#table-of-contents) | :passenger_ship: | `:passenger_ship:`  |  :pause_button: | `:pause_button:` |
| [top](#table-of-contents) | :peace_symbol: | `:peace_symbol:`  |  :peanuts: | `:peanuts:` |
| [top](#table-of-contents) | :pen: | `:pen:`  |  :person_fencing: | `:person_fencing:` |
| [top](#table-of-contents) | :peru: | `:peru:`  |  :philippines: | `:philippines:` |
| [top](#table-of-contents) | :pick: | `:pick:`  |  :ping_pong: | `:ping_pong:` |
| [top](#table-of-contents) | :pitcairn_islands: | `:pitcairn_islands:`  |  :place_of_worship: | `:place_of_worship:` |
| [top](#table-of-contents) | :plate_with_cutlery: | `:plate_with_cutlery:`  |  :play_or_pause_button: | `:play_or_pause_button:` |
| [top](#table-of-contents) | :poland: | `:poland:`  |  :policeman: | `:policeman:` |
| [top](#table-of-contents) | :policewoman: | `:policewoman:`  |  :popcorn: | `:popcorn:` |
| [top](#table-of-contents) | :portugal: | `:portugal:`  |  :potato: | `:potato:` |
| [top](#table-of-contents) | :pout: | `:pout:`  |  :pouting_man: | `:pouting_man:` |
| [top](#table-of-contents) | :pouting_woman: | `:pouting_woman:`  |  :prayer_beads: | `:prayer_beads:` |
| [top](#table-of-contents) | :pregnant_woman: | `:pregnant_woman:`  |  :previous_track_button: | `:previous_track_button:` |
| [top](#table-of-contents) | :prince: | `:prince:`  |  :printer: | `:printer:` |
| [top](#table-of-contents) | :puerto_rico: | `:puerto_rico:`  |  :qatar: | `:qatar:` |
| [top](#table-of-contents) | :racing_car: | `:racing_car:`  |  :radioactive: | `:radioactive:` |
| [top](#table-of-contents) | :railway_track: | `:railway_track:`  |  :rainbow_flag: | `:rainbow_flag:` |
| [top](#table-of-contents) | :raised_back_of_hand: | `:raised_back_of_hand:`  |  :raised_hand_with_fingers_splayed: | `:raised_hand_with_fingers_splayed:` |
| [top](#table-of-contents) | :raising_hand_man: | `:raising_hand_man:`  |  :raising_hand_woman: | `:raising_hand_woman:` |
| [top](#table-of-contents) | :record_button: | `:record_button:`  |  :reminder_ribbon: | `:reminder_ribbon:` |
| [top](#table-of-contents) | :rescue_worker_helmet: | `:rescue_worker_helmet:`  |  :reunion: | `:reunion:` |
| [top](#table-of-contents) | :rhinoceros: | `:rhinoceros:`  |  :right_anger_bubble: | `:right_anger_bubble:` |
| [top](#table-of-contents) | :robot: | `:robot:`  |  :rofl: | `:rofl:` |
| [top](#table-of-contents) | :roll_eyes: | `:roll_eyes:`  |  :romania: | `:romania:` |
| [top](#table-of-contents) | :rosette: | `:rosette:`  |  :rowing_man: | `:rowing_man:` |
| [top](#table-of-contents) | :rowing_woman: | `:rowing_woman:`  |  :running_man: | `:running_man:` |
| [top](#table-of-contents) | :running_woman: | `:running_woman:`  |  :rwanda: | `:rwanda:` |
| [top](#table-of-contents) | :samoa: | `:samoa:`  |  :san_marino: | `:san_marino:` |
| [top](#table-of-contents) | :sao_tome_principe: | `:sao_tome_principe:`  |  :saudi_arabia: | `:saudi_arabia:` |
| [top](#table-of-contents) | :scorpion: | `:scorpion:`  |  :selfie: | `:selfie:` |
| [top](#table-of-contents) | :senegal: | `:senegal:`  |  :serbia: | `:serbia:` |
| [top](#table-of-contents) | :seychelles: | `:seychelles:`  |  :shallow_pan_of_food: | `:shallow_pan_of_food:` |
| [top](#table-of-contents) | :shamrock: | `:shamrock:`  |  :shark: | `:shark:` |
| [top](#table-of-contents) | :shield: | `:shield:`  |  :shinto_shrine: | `:shinto_shrine:` |
| [top](#table-of-contents) | :shopping: | `:shopping:`  |  :shopping_cart: | `:shopping_cart:` |
| [top](#table-of-contents) | :shrimp: | `:shrimp:`  |  :sierra_leone: | `:sierra_leone:` |
| [top](#table-of-contents) | :singapore: | `:singapore:`  |  :sint_maarten: | `:sint_maarten:` |
| [top](#table-of-contents) | :skier: | `:skier:`  |  :skull_and_crossbones: | `:skull_and_crossbones:` |
| [top](#table-of-contents) | :sleeping_bed: | `:sleeping_bed:`  |  :slightly_frowning_face: | `:slightly_frowning_face:` |
| [top](#table-of-contents) | :slightly_smiling_face: | `:slightly_smiling_face:`  |  :slovakia: | `:slovakia:` |
| [top](#table-of-contents) | :slovenia: | `:slovenia:`  |  :small_airplane: | `:small_airplane:` |
| [top](#table-of-contents) | :sneezing_face: | `:sneezing_face:`  |  :snowman_with_snow: | `:snowman_with_snow:` |
| [top](#table-of-contents) | :solomon_islands: | `:solomon_islands:`  |  :somalia: | `:somalia:` |
| [top](#table-of-contents) | :south_africa: | `:south_africa:`  |  :south_georgia_south_sandwich_islands: | `:south_georgia_south_sandwich_islands:` |
| [top](#table-of-contents) | :south_sudan: | `:south_sudan:`  |  :speaking_head: | `:speaking_head:` |
| [top](#table-of-contents) | :spider: | `:spider:`  |  :spider_web: | `:spider_web:` |
| [top](#table-of-contents) | :spiral_calendar: | `:spiral_calendar:`  |  :spiral_notepad: | `:spiral_notepad:` |
| [top](#table-of-contents) | :spoon: | `:spoon:`  |  :squid: | `:squid:` |
| [top](#table-of-contents) | :sri_lanka: | `:sri_lanka:`  |  :st_barthelemy: | `:st_barthelemy:` |
| [top](#table-of-contents) | :st_helena: | `:st_helena:`  |  :st_kitts_nevis: | `:st_kitts_nevis:` |
| [top](#table-of-contents) | :st_lucia: | `:st_lucia:`  |  :st_pierre_miquelon: | `:st_pierre_miquelon:` |
| [top](#table-of-contents) | :st_vincent_grenadines: | `:st_vincent_grenadines:`  |  :stadium: | `:stadium:` |
| [top](#table-of-contents) | :star_and_crescent: | `:star_and_crescent:`  |  :star_of_david: | `:star_of_david:` |
| [top](#table-of-contents) | :stop_button: | `:stop_button:`  |  :stop_sign: | `:stop_sign:` |
| [top](#table-of-contents) | :stopwatch: | `:stopwatch:`  |  :studio_microphone: | `:studio_microphone:` |
| [top](#table-of-contents) | :stuffed_flatbread: | `:stuffed_flatbread:`  |  :sudan: | `:sudan:` |
| [top](#table-of-contents) | :sun_behind_large_cloud: | `:sun_behind_large_cloud:`  |  :sun_behind_rain_cloud: | `:sun_behind_rain_cloud:` |
| [top](#table-of-contents) | :sun_behind_small_cloud: | `:sun_behind_small_cloud:`  |  :surfing_man: | `:surfing_man:` |
| [top](#table-of-contents) | :surfing_woman: | `:surfing_woman:`  |  :suriname: | `:suriname:` |
| [top](#table-of-contents) | :swaziland: | `:swaziland:`  |  :sweden: | `:sweden:` |
| [top](#table-of-contents) | :swimming_man: | `:swimming_man:`  |  :swimming_woman: | `:swimming_woman:` |
| [top](#table-of-contents) | :switzerland: | `:switzerland:`  |  :synagogue: | `:synagogue:` |
| [top](#table-of-contents) | :syria: | `:syria:`  |  :taco: | `:taco:` |
| [top](#table-of-contents) | :taiwan: | `:taiwan:`  |  :tajikistan: | `:tajikistan:` |
| [top](#table-of-contents) | :tanzania: | `:tanzania:`  |  :thailand: | `:thailand:` |
| [top](#table-of-contents) | :thermometer: | `:thermometer:`  |  :thinking: | `:thinking:` |
| [top](#table-of-contents) | :tickets: | `:tickets:`  |  :timer_clock: | `:timer_clock:` |
| [top](#table-of-contents) | :timor_leste: | `:timor_leste:`  |  :tipping_hand_man: | `:tipping_hand_man:` |
| [top](#table-of-contents) | :tipping_hand_woman: | `:tipping_hand_woman:`  |  :togo: | `:togo:` |
| [top](#table-of-contents) | :tokelau: | `:tokelau:`  |  :tonga: | `:tonga:` |
| [top](#table-of-contents) | :tornado: | `:tornado:`  |  :tr: | `:tr:` |
| [top](#table-of-contents) | :trackball: | `:trackball:`  |  :trinidad_tobago: | `:trinidad_tobago:` |
| [top](#table-of-contents) | :tumbler_glass: | `:tumbler_glass:`  |  :tunisia: | `:tunisia:` |
| [top](#table-of-contents) | :turkey: | `:turkey:`  |  :turkmenistan: | `:turkmenistan:` |
| [top](#table-of-contents) | :turks_caicos_islands: | `:turks_caicos_islands:`  |  :tuvalu: | `:tuvalu:` |
| [top](#table-of-contents) | :uganda: | `:uganda:`  |  :ukraine: | `:ukraine:` |
| [top](#table-of-contents) | :unicorn: | `:unicorn:`  |  :united_arab_emirates: | `:united_arab_emirates:` |
| [top](#table-of-contents) | :upside_down_face: | `:upside_down_face:`  |  :uruguay: | `:uruguay:` |
| [top](#table-of-contents) | :us_virgin_islands: | `:us_virgin_islands:`  |  :uzbekistan: | `:uzbekistan:` |
| [top](#table-of-contents) | :vanuatu: | `:vanuatu:`  |  :vatican_city: | `:vatican_city:` |
| [top](#table-of-contents) | :venezuela: | `:venezuela:`  |  :vietnam: | `:vietnam:` |
| [top](#table-of-contents) | :volleyball: | `:volleyball:`  |  :vulcan_salute: | `:vulcan_salute:` |
| [top](#table-of-contents) | :walking: | `:walking:`  |  :walking_man: | `:walking_man:` |
| [top](#table-of-contents) | :walking_woman: | `:walking_woman:`  |  :wallis_futuna: | `:wallis_futuna:` |
| [top](#table-of-contents) | :wastebasket: | `:wastebasket:`  |  :weight_lifting_man: | `:weight_lifting_man:` |
| [top](#table-of-contents) | :weight_lifting_woman: | `:weight_lifting_woman:`  |  :western_sahara: | `:western_sahara:` |
| [top](#table-of-contents) | :wheel_of_dharma: | `:wheel_of_dharma:`  |  :white_flag: | `:white_flag:` |
| [top](#table-of-contents) | :wilted_flower: | `:wilted_flower:`  |  :wind_face: | `:wind_face:` |
| [top](#table-of-contents) | :woman_artist: | `:woman_artist:`  |  :woman_astronaut: | `:woman_astronaut:` |
| [top](#table-of-contents) | :woman_cartwheeling: | `:woman_cartwheeling:`  |  :woman_cook: | `:woman_cook:` |
| [top](#table-of-contents) | :woman_facepalming: | `:woman_facepalming:`  |  :woman_factory_worker: | `:woman_factory_worker:` |
| [top](#table-of-contents) | :woman_farmer: | `:woman_farmer:`  |  :woman_firefighter: | `:woman_firefighter:` |
| [top](#table-of-contents) | :woman_health_worker: | `:woman_health_worker:`  |  :woman_judge: | `:woman_judge:` |
| [top](#table-of-contents) | :woman_juggling: | `:woman_juggling:`  |  :woman_mechanic: | `:woman_mechanic:` |
| [top](#table-of-contents) | :woman_office_worker: | `:woman_office_worker:`  |  :woman_pilot: | `:woman_pilot:` |
| [top](#table-of-contents) | :woman_playing_handball: | `:woman_playing_handball:`  |  :woman_playing_water_polo: | `:woman_playing_water_polo:` |
| [top](#table-of-contents) | :woman_scientist: | `:woman_scientist:`  |  :woman_shrugging: | `:woman_shrugging:` |
| [top](#table-of-contents) | :woman_singer: | `:woman_singer:`  |  :woman_student: | `:woman_student:` |
| [top](#table-of-contents) | :woman_teacher: | `:woman_teacher:`  |  :woman_technologist: | `:woman_technologist:` |
| [top](#table-of-contents) | :woman_with_turban: | `:woman_with_turban:`  |  :women_wrestling: | `:women_wrestling:` |
| [top](#table-of-contents) | :world_map: | `:world_map:`  |  :writing_hand: | `:writing_hand:` |
| [top](#table-of-contents) | :yemen: | `:yemen:`  |  :yin_yang: | `:yin_yang:` |
| [top](#table-of-contents) | :zambia: | `:zambia:`  |  :zimbabwe: | `:zimbabwe:` |
| [top](#table-of-contents) | :zipper_mouth_face: | `:zipper_mouth_face:`  |  | |
